plugins {
    id "net.neoforged.moddev" version "1.0.11"
}

version = rootProject.neoforge_mod_version
group = rootProject.maven_group

base {
    archivesName = "${rootProject.archives_base_name}-neoforge"
}

repositories {
    mavenCentral()
    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases/"
    }
}

neoForge {
    version = rootProject.neoforge_version

    mods {
        animon_fix {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly files(rootProject.cobblemon_neoforge_jar)
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.3"
    testImplementation "org.ow2.asm:asm-tree:9.7.1"
    testRuntimeOnly files(sourceSets.main.compileClasspath)
}

test {
    useJUnitPlatform()
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
